// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.shuangyangad.mta.event;

public interface EventRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.EventRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event = 1;</code>
   * @return The event.
   */
  java.lang.String getEvent();
  /**
   * <code>string event = 1;</code>
   * @return The bytes for event.
   */
  com.google.protobuf.ByteString
      getEventBytes();
}
