// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.shuangyangad.mta.event;

public interface EventResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:event.EventResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 code = 2;</code>
   * @return The code.
   */
  int getCode();
}
