// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package com.shuangyangad.mta.event;

public final class Event {
  private Event() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_EventRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_EventRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_event_EventResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_event_EventResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\005event\"\035\n\014EventRequest\022\r\n\005" +
      "event\030\001 \001(\t\".\n\rEventResponse\022\017\n\007message\030" +
      "\001 \001(\t\022\014\n\004code\030\002 \001(\0052?\n\007Greeter\0224\n\005track\022" +
      "\023.event.EventRequest\032\024.event.EventRespon" +
      "se\"\000B+\n\032com.shuangyangad.mta.eventB\005Even" +
      "tP\001\242\002\003HLWb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_event_EventRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_event_EventRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_EventRequest_descriptor,
        new java.lang.String[] { "Event", });
    internal_static_event_EventResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_event_EventResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_event_EventResponse_descriptor,
        new java.lang.String[] { "Message", "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
